/**
 * api
 * Tiblar is a privacy center media sharing site https://tiblar.com/support/pages/mission 
 *
 * OpenAPI spec version: v2
 * Contact: support@tiblar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DebugApi {

  /**
   * pong
   * 
   * Expected answers:
   *   code 200 :  (API is up)
   *   code 404 :  (API is down)
   */
  def ping(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/Tiblar/Tiblar-v2/v2", "/ping", "application/json")
      .withSuccessResponse[Unit](200)
      .withErrorResponse[Unit](404)
      

}

