/**
 * api
 * Tiblar is a privacy center media sharing site https://tiblar.com/support/pages/mission 
 *
 * OpenAPI spec version: v2
 * Contact: support@tiblar.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class User (
  id: Option[String] = None,
  info: Option[Info] = None,
  privacy: Option[Privacy] = None,
  verified: Option[Boolean] = None,
  roles: Option[Seq[String]] = None,
  boosted: Option[Boolean] = None,
  banned: Option[Boolean] = None,
  connections: Option[Connection] = None
) extends ApiModel


